export const brandConstants = {
  ADD_REQUEST: 'BRANDS_ADD_REQUEST',
  ADD_SUCCESS: 'BRANDS_ADD_SUCCESS',
  ADD_FAILURE: 'BRANDS_ADD_FAILURE',

  GETALL_REQUEST: 'BRANDS_GETALL_REQUEST',
  GETALL_SUCCESS: 'BRANDS_GETALL_SUCCESS',
  GETALL_FAILURE: 'BRANDS_GETALL_FAILURE',

  DELETE_REQUEST: 'BRANDS_DELETE_REQUEST',
  DELETE_SUCCESS: 'BRANDS_DELETE_SUCCESS',
  DELETE_FAILURE: 'BRANDS_DELETE_FAILURE',

  UPDATE_REQUEST: 'BRANDS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'BRANDS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'BRANDS_UPDATE_FAILURE',
};
