export const customerConstants = {
  ADD_REQUEST: 'CUSTOMERS_ADD_REQUEST',
  ADD_SUCCESS: 'CUSTOMERS_ADD_SUCCESS',
  ADD_FAILURE: 'CUSTOMERS_ADD_FAILURE',

  GETALL_REQUEST: 'CUSTOMERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'CUSTOMERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'CUSTOMERS_GETALL_FAILURE',

  DELETE_REQUEST: 'CUSTOMERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'CUSTOMERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'CUSTOMERS_DELETE_FAILURE',

  UPDATE_REQUEST: 'CUSTOMERS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'CUSTOMERS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'CUSTOMERS_UPDATE_FAILURE',
};
