export const productConstants = {
  ADD_REQUEST: 'PRODUCTS_ADD_REQUEST',
  ADD_SUCCESS: 'PRODUCTS_ADD_SUCCESS',
  ADD_FAILURE: 'PRODUCTS_ADD_FAILURE',

  GETALL_REQUEST: 'PRODUCTS_GETALL_REQUEST',
  GETALL_SUCCESS: 'PRODUCTS_GETALL_SUCCESS',
  GETALL_FAILURE: 'PRODUCTS_GETALL_FAILURE',

  DELETE_REQUEST: 'PRODUCTS_DELETE_REQUEST',
  DELETE_SUCCESS: 'PRODUCTS_DELETE_SUCCESS',
  DELETE_FAILURE: 'PRODUCTS_DELETE_FAILURE',

  UPDATE_REQUEST: 'PRODUCTS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'PRODUCTS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'PRODUCTS_UPDATE_FAILURE',
};
