export const supplierConstants = {
  ADD_REQUEST: 'SUPPLIERS_ADD_REQUEST',
  ADD_SUCCESS: 'SUPPLIERS_ADD_SUCCESS',
  ADD_FAILURE: 'SUPPLIERS_ADD_FAILURE',

  GETALL_REQUEST: 'SUPPLIERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'SUPPLIERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'SUPPLIERS_GETALL_FAILURE',

  DELETE_REQUEST: 'SUPPLIERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'SUPPLIERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'SUPPLIERS_DELETE_FAILURE',

  UPDATE_REQUEST: 'SUPPLIERS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'SUPPLIERS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'SUPPLIERS_UPDATE_FAILURE',
};
